### ISSUE TITLE
export the pre-trained model to ONNX and blob compatible with OAK-D device

### ISSUE THREAD

**Issue by jimas95** [tersekmatija/eWaSR#8]
Awesome work! looking forward to test it using an OAK-D camera!
I am encountering an issue while trying to convert the model to onnx. 

`
Traceback (most recent call last):
  File "eWaSR\export.py", line 106, in <module>
    main()
  File "eWaSR\export.py", line 103, in main
    export(args)
  File "eWaSR\export.py", line 57, in export
    torch.onnx.export(
  File "env_python_obstacle_detection\Lib\site-packages\torch\onnx\utils.py", line 516, in export
    _export(
  File "env_python_obstacle_detection\Lib\site-packages\torch\onnx\utils.py", line 1613, in _export
    graph, params_dict, torch_out = _model_to_graph(
                                    ^^^^^^^^^^^^^^^^
  File "env_python_obstacle_detection\Lib\site-packages\torch\onnx\utils.py", line 1139, in _model_to_graph       
    graph = _optimize_graph(
            ^^^^^^^^^^^^^^^^
  File "env_python_obstacle_detection\Lib\site-packages\torch\onnx\utils.py", line 677, in _optimize_graph        
    graph = _C._jit_pass_onnx(graph, operator_export_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env_python_obstacle_detection\Lib\site-packages\torch\onnx\utils.py", line 1967, in _run_symbolic_function
    raise errors.UnsupportedOperatorError(
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::_upsample_bilinear2d_aa' to ONNX opset version 12 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
`

Issue is happening while it attempts to export the model to onnx. I did find a related [issue ](https://github.com/pytorch/pytorch/issues/22906) mentioning that setting opset_version=12 to 11 would fix it but no luck. 
Issue persist with either imu or not. 
Lib versions are :
1. torch 2.2.1+cpu
2. onnx 1.15.0

**Comment by jimas95** [comment]
Update: downgrading torch to 2.0.0 fixed the issue

**Comment by tersekmatija** [comment]
Thanks, closing the issue as downgraded version works.
